services:
  postgres:
    image: postgres:15
    container_name: postgres_gerenciamentoprodutos
    environment:
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: root
      POSTGRES_DB: produtosdb
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data